spring.datasource.url=jdbc:postgresql://PROD_HOST:5432/razorpay_prod_db
spring.datasource.username=PROD_USER
spring.datasource.password=PROD_PASSWORD

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false